// Flat US map shown when an entire career is US-based. Renders state outlines,
// an era-colored dot per located role, and animated arcs tracing the journey
// between consecutive roles — the 2D counterpart to <Globe/>. Fully offline:
// state geometry is vendored at src/lib/us-states.geo.json.
import { useMemo } from 'react';
import { geoAlbersUsa, geoPath } from 'd3-geo';
import type { FeatureCollection, MultiPolygon, Polygon } from 'geojson';
import type { CareerProfile, Era } from '../lib/types';
import { ERA_COLOR } from '../lib/eras';
import rawStatesGeo from '../lib/us-states.geo.json';

// The vendored JSON resolves to a loose inferred type; assert the GeoJSON shape
// d3-geo expects. (Geometry was generated by scripts/build-us-geo.mjs.)
const statesGeo = rawStatesGeo as unknown as FeatureCollection<
  Polygon | MultiPolygon,
  { name: string }
>;

// Fixed projection space; the SVG scales to its container via viewBox + CSS.
const W = 960;
const H = 600;
const projection = geoAlbersUsa().fitSize([W, H], statesGeo);
const pathGen = geoPath(projection);
const STATE_PATHS = statesGeo.features
  .map((f) => pathGen(f))
  .filter((d): d is string => d != null);

interface Plotted {
  x: number;
  y: number;
  era: Era;
  r: number;
  label: string;
}

interface Arc {
  d: string;
  from: Era;
  to: Era;
  id: string;
}

export default function UsMap({ profile }: { profile: CareerProfile }) {
  const { dots, arcs } = useMemo(() => {
    const dots: Plotted[] = [];
    for (const n of profile.nodes) {
      if (!n.location) continue;
      const xy = projection([n.location.lng, n.location.lat]);
      if (!xy) continue; // outside the AlbersUsa frame
      dots.push({
        x: xy[0],
        y: xy[1],
        era: n.era,
        r: 4 + n.aiRelevance * 7,
        label: `${n.role} · ${n.employer} (${n.location.city})`,
      });
    }
    const arcs: Arc[] = [];
    for (let i = 1; i < dots.length; i++) {
      const a = dots[i - 1];
      const b = dots[i];
      const len = Math.hypot(b.x - a.x, b.y - a.y);
      const mx = (a.x + b.x) / 2;
      const my = (a.y + b.y) / 2 - len * 0.28; // bow the arc upward
      arcs.push({
        d: `M${a.x},${a.y} Q${mx},${my} ${b.x},${b.y}`,
        from: a.era,
        to: b.era,
        id: `arc-${i}`,
      });
    }
    return { dots, arcs };
  }, [profile]);

  return (
    <div className="us-map-wrap">
      <svg viewBox={`0 0 ${W} ${H}`} className="us-map" role="img" aria-label="US career map">
        <defs>
          {arcs.map((arc) => (
            <linearGradient key={arc.id} id={arc.id} gradientUnits="userSpaceOnUse">
              <stop offset="0%" stopColor={ERA_COLOR[arc.from]} />
              <stop offset="100%" stopColor={ERA_COLOR[arc.to]} />
            </linearGradient>
          ))}
        </defs>

        <g className="us-states">
          {STATE_PATHS.map((d, i) => (
            <path key={i} d={d} />
          ))}
        </g>

        <g className="us-arcs">
          {arcs.map((arc) => (
            <path key={arc.id} d={arc.d} stroke={`url(#${arc.id})`} />
          ))}
        </g>

        <g className="us-dots">
          {dots.map((p, i) => (
            <g key={i} transform={`translate(${p.x},${p.y})`}>
              <circle className="us-dot-halo" r={p.r * 2.2} fill={ERA_COLOR[p.era]} />
              <circle r={p.r} fill={ERA_COLOR[p.era]}>
                <title>{p.label}</title>
              </circle>
            </g>
          ))}
        </g>
      </svg>
    </div>
  );
}
