// Flat US map shown when an entire career is US-based. Renders state outlines,
// an era-colored dot per worked city, and animated arcs tracing the journey
// between consecutive roles — the 2D counterpart to <Globe/>. Clicking a dot
// opens a description of the role(s) worked there, mirroring the globe's
// country panel. Fully offline: state geometry is vendored at
// src/lib/us-states.geo.json.
import { useMemo, useState } from 'react';
import { geoAlbersUsa, geoPath } from 'd3-geo';
import type { FeatureCollection, MultiPolygon, Polygon } from 'geojson';
import type { CareerNode, CareerProfile, Era } from '../lib/types';
import { ERA_COLOR } from '../lib/eras';
import rawStatesGeo from '../lib/us-states.geo.json';

// The vendored JSON resolves to a loose inferred type; assert the GeoJSON shape
// d3-geo expects. (Geometry was generated by scripts/build-us-geo.mjs.)
const statesGeo = rawStatesGeo as unknown as FeatureCollection<
  Polygon | MultiPolygon,
  { name: string }
>;

// Fixed projection space; the SVG scales to its container via viewBox + CSS.
const W = 960;
const H = 600;
const projection = geoAlbersUsa().fitSize([W, H], statesGeo);
const pathGen = geoPath(projection);
const STATE_PATHS = statesGeo.features
  .map((f) => pathGen(f))
  .filter((d): d is string => d != null);

interface CityDot {
  key: string;
  name: string; // "Gainesville, FL"
  x: number;
  y: number;
  era: Era;
  r: number;
  roles: CareerNode[];
}

interface Arc {
  d: string;
  from: Era;
  to: Era;
  id: string;
}

export default function UsMap({ profile }: { profile: CareerProfile }) {
  const [selected, setSelected] = useState<string | null>(null);

  const { cityDots, arcs } = useMemo(() => {
    // Per-node projected points drive the journey arcs.
    const pts: { x: number; y: number; node: CareerNode }[] = [];
    for (const n of profile.nodes) {
      if (!n.location) continue;
      const xy = projection([n.location.lng, n.location.lat]);
      if (!xy) continue; // outside the AlbersUsa frame
      pts.push({ x: xy[0], y: xy[1], node: n });
    }

    const arcs: Arc[] = [];
    for (let i = 1; i < pts.length; i++) {
      const a = pts[i - 1];
      const b = pts[i];
      if (a.x === b.x && a.y === b.y) continue; // same city — no visible arc
      const len = Math.hypot(b.x - a.x, b.y - a.y);
      const mx = (a.x + b.x) / 2;
      const my = (a.y + b.y) / 2 - len * 0.28; // bow the arc upward
      arcs.push({
        d: `M${a.x},${a.y} Q${mx},${my} ${b.x},${b.y}`,
        from: a.node.era,
        to: b.node.era,
        id: `arc-${i}`,
      });
    }

    // Group roles by city so a single dot can describe every role worked there.
    const byCity = new Map<string, CityDot>();
    for (const p of pts) {
      const loc = p.node.location!;
      const key = `${loc.city}|${loc.state ?? loc.country ?? ''}`;
      const name = loc.state ? `${loc.city}, ${loc.state}` : loc.city;
      const existing = byCity.get(key);
      if (existing) {
        existing.roles.push(p.node);
      } else {
        byCity.set(key, { key, name, x: p.x, y: p.y, era: p.node.era, r: 0, roles: [p.node] });
      }
    }
    const cityDots = [...byCity.values()].map((d) => {
      const latest = d.roles[d.roles.length - 1];
      const maxAi = Math.max(...d.roles.map((n) => n.aiRelevance));
      return { ...d, era: latest.era, r: 4 + maxAi * 7 };
    });

    return { cityDots, arcs };
  }, [profile]);

  const selectedDot = selected ? cityDots.find((d) => d.key === selected) : undefined;

  return (
    <div className="us-map-wrap">
      <svg viewBox={`0 0 ${W} ${H}`} className="us-map" role="img" aria-label="US career map">
        <defs>
          {arcs.map((arc) => (
            <linearGradient key={arc.id} id={arc.id} gradientUnits="userSpaceOnUse">
              <stop offset="0%" stopColor={ERA_COLOR[arc.from]} />
              <stop offset="100%" stopColor={ERA_COLOR[arc.to]} />
            </linearGradient>
          ))}
        </defs>

        <g className="us-states">
          {STATE_PATHS.map((d, i) => (
            <path key={i} d={d} />
          ))}
        </g>

        <g className="us-arcs">
          {arcs.map((arc) => (
            <path key={arc.id} d={arc.d} stroke={`url(#${arc.id})`} />
          ))}
        </g>

        <g className="us-dots">
          {cityDots.map((p) => {
            const active = p.key === selected;
            return (
              <g
                key={p.key}
                transform={`translate(${p.x},${p.y})`}
                className={`us-dot ${active ? 'active' : ''}`}
                onClick={() => setSelected((cur) => (cur === p.key ? null : p.key))}
                role="button"
                aria-label={`${p.name} — ${p.roles.length} role${p.roles.length > 1 ? 's' : ''}`}
              >
                {active && (
                  <circle className="us-dot-ring" r={p.r + 6} fill="none" stroke={ERA_COLOR[p.era]} />
                )}
                <circle className="us-dot-halo" r={p.r * 2.2} fill={ERA_COLOR[p.era]} />
                <circle r={p.r} fill={ERA_COLOR[p.era]}>
                  <title>
                    {p.name} — {p.roles.length} role{p.roles.length > 1 ? 's' : ''}
                  </title>
                </circle>
              </g>
            );
          })}
        </g>
      </svg>

      {selectedDot && (
        <aside className="country-card">
          <header className="country-card-head">
            <span className="country-card-name">{selectedDot.name}</span>
            <button
              className="country-card-close"
              onClick={() => setSelected(null)}
              aria-label="Close"
            >
              ×
            </button>
          </header>
          <ul className="country-card-roles">
            {selectedDot.roles.map((n) => (
              <li key={n.id} className={`country-role era-${n.era}`}>
                <div className="country-role-title">{n.role}</div>
                <div className="country-role-meta">
                  {n.employer} · {n.location!.city} · {n.start} – {n.end}
                </div>
                {n.summary && <p className="country-role-summary">{n.summary}</p>}
                {n.highlights.length > 0 && (
                  <ul className="country-role-highlights">
                    {n.highlights.slice(0, 3).map((h, i) => (
                      <li key={i}>{h}</li>
                    ))}
                  </ul>
                )}
              </li>
            ))}
          </ul>
        </aside>
      )}
    </div>
  );
}
